<a href="https://colab.research.google.com/github/ChidanandaBhattacharjee/machine-learning/blob/main/Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Part 1 - Data Preprocessing

### Importing the dataset

In [2]:
dataset=pd.read_excel('Folds5x2_pp.xlsx')
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [3]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [4]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

## Part 2 - Building the ANN

### Initializing the ANN

In [11]:
ann=tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the second hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the output layer

In [14]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [15]:
ann.compile(optimizer='adam',loss='mean_squared_error')

### Training the ANN model on the Training set

In [16]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 888us/step - loss: 83845.1973
Epoch 2/100
240/240 [==============================] - 0s 960us/step - loss: 437.7872
Epoch 3/100
240/240 [==============================] - 0s 891us/step - loss: 333.5665
Epoch 4/100
240/240 [==============================] - 0s 897us/step - loss: 304.4972
Epoch 5/100
240/240 [==============================] - 0s 899us/step - loss: 271.9706
Epoch 6/100
240/240 [==============================] - 0s 897us/step - loss: 250.4266
Epoch 7/100
240/240 [==============================] - 0s 897us/step - loss: 211.5744
Epoch 8/100
240/240 [==============================] - 0s 895us/step - loss: 178.9418
Epoch 9/100
240/240 [==============================] - 0s 889us/step - loss: 151.7646
Epoch 10/100
240/240 [==============================] - 0s 856us/step - loss: 122.7842
Epoch 11/100
240/240 [==============================] - 0s 896us/step - loss: 102.7816
Epoch 12/100
240/240 [============================

### Predicting the results of the Test set

In [17]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[432.07 431.23]
 [462.94 460.01]
 [466.41 461.14]
 ...
 [473.63 473.26]
 [440.5  438.  ]
 [459.63 463.28]]
